export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const TRIP_HISTORY_COMPLETED = 'TRIP_HISTORY_COMPLETED';
export const SINGLE_HISTORY_COMPLETED = 'SINGLE_HISTORY_COMPLETED';
export const TRIP_HISTORY_OTHERS = 'TRIP_HISTORY_OTHERS';
export const SINGLE_HISTORY_OTHERS = 'SINGLE_HISTORY_OTHERS';
export const TRIGGER_HISTORY_GET = 'TRIGGER_HISTORY_GET';
export const DELIVER_TRIP = 'DELIVER_TRIP';