export const LOADING = 'LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const PREVIOUS_WEEK_NET = 'PREVIOUS_WEEK_NET';
export const CURRENT_WEEK_NET = 'CURRENT_WEEK_NET';
export const THREE_MONTH_NET = 'THREE_MONTH_NET';
export const NET_PREVIOUS_WEEK_DISPLAY = 'NET_PREVIOUS_WEEK_DISPLAY';
export const NET_CURRENT_WEEK_DISPLAY = 'NET_CURRENT_WEEK_DISPLAY';
export const NET_THREE_MONTH_DISPLAY = 'NET_THREE_MONTH_DISPLAY';

export const PREVIOUS_WEEK_REVENUE = 'PREVIOUS_WEEK_REVENUE';
export const CURRENT_WEEK_REVENUE = 'CURRENT_WEEK_REVENUE';
export const THREE_MONTH_REVENUE = 'THREE_MONTH_REVENUE';
export const REVENUE_PREVIOUS_WEEK_DISPLAY = 'REVENUE_PREVIOUS_WEEK_DISPLAY';
export const REVENUE_CURRENT_WEEK_DISPLAY = 'REVENUE_CURRENT_WEEK_DISPLAY';
export const REVENUE_THREE_MONTH_DISPLAY = 'REVENUE_THREE_MONTH_DISPLAY';

export const PREVIOUS_WEEK_BALANCE = 'PREVIOUS_WEEK_BALANCE';
export const CURRENT_WEEK_BALANCE = 'CURRENT_WEEK_BALANCE';
export const THREE_MONTH_BALANCE = 'THREE_MONTH_BALANCE';
export const BALANCE_PREVIOUS_WEEK_DISPLAY = 'BALANCE_PREVIOUS_WEEK_DISPLAY';
export const BALANCE_CURRENT_WEEK_DISPLAY = 'BALANCE_CURRENT_WEEK_DISPLAY';
export const BALANCE_THREE_MONTH_DISPLAY = 'BALANCE_THREE_MONTH_DISPLAY';